# ----------------------------------------------------------------------
#
# Fastfile
# https://docs.fastlane.tools
#
# ----------------------------------------------------------------------

require 'simctl'

lane :test do
	runtime = SimCtl.runtime(name: 'iOS 15.5')
	UI.message runtime
end
